### ISSUE TITLE
Implement the wireframes v1.0

### ISSUE THREAD

**Issue by tomm1990** [shenkarlab/HolyShic#14]
**1. static**
**2. responsive**
**3. hover**
4. initial clicks

**Comment by tomm1990** [comment]
<img width="642" alt="screen shot 2017-01-04 at 15 01 29" src="https://cloud.githubusercontent.com/assets/15614458/21643033/bbee44f4-d28e-11e6-81e2-c3a9c1900513.png">

**Comment by yahav10** [comment]
Done.

<img width="1280" alt="screen shot 2017-01-07 at 19 43 22" src="https://cloud.githubusercontent.com/assets/15280673/21743765/a1c19bfa-d511-11e6-894f-fabc10a2683b.png">
